# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      
    - name: Run test
      run: dotnet test TestWebService.Integration.Tests --logger "trx;LogFileName=vault_test_results.xml" --results-directory "test_results"
      continue-on-error: true
      
    - uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: test_results
        path: test-results.xml
        
    - uses: dorny/test-reporter@v1.9.0
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Ruby Decom Tests            
        path: test_results/vault_test_results.xml  
        reporter: dotnet-trx
